---
abstract: 'Use CHI Caches in Mojolicious'
author:
  - 'Nils Diewald'
build_requires:
  Test::More: '0'
  Test::Output: '1'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-CHI
no_index:
  directory:
    - t
    - inc
requires:
  CHI: '0'
  Mojolicious: '4.77'
  perl: '5.010001'
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/Akron/Mojolicious-Plugin-CHI
version: 0.08_3
